#!/usr/bin/python
import locale
import sys
from coinbase.wallet.client import Client

locale.setlocale(locale.LC_MONETARY, 'en_US.utf8')

api_key = "***REMOVED***"
api_secret = "***REMOVED***"
#api_version = "2017-12-14"

try:
    client = Client(api_key, api_secret)
    #client.API_VERSION = api_version
except:
    print("Error, Probably API version.")
    sys.exit()

accounts = client.get_accounts()
bch_account = (b for b in accounts['data'] if b['balance']['currency'] == 'BCH').__next__()
bch_bal = bch_account.get('native_balance')
# aa = bch.__next__()
# bb = aa.get('amount')
# fbchbal = str(bch)
fbchbal = str(bch_bal)[3:]
cfbchbal = locale.currency(float(fbchbal), grouping=True)

bal = client.get_primary_account().get("native_balance")
fbal = str(bal)[3:]
cfbal = locale.currency(float(fbal), grouping=True)

btctousd = client.get_spot_price().get("amount")
fbtctousd = locale.currency(float(btctousd), grouping=True)

bchtousd = client.get_spot_price(currency_pair='BCH-USD').get("amount")
fbchtousd = locale.currency(float(bchtousd), grouping=True)

totalbal = float(fbchbal) + float(fbal)
ftotalbal = locale.currency(float(totalbal), grouping=True)


if "USD" in str(bal):
    print(f' {cfbal} ||  {fbtctousd} ||| BCH {cfbchbal} |||| TOTAL: {ftotalbal} ')
