#!/usr/bin/python3.6

import urllib.request, json

city = "Traverse City"
#city = "Chicago"
api_key = "60309dc74f095fe90e1f113b726f1ca7"

units_metric = "Metric"
units_us = "Imperial"

unit_key_c = "C"
unit_key_f = "F"



weather_c = eval(str(urllib.request.urlopen(f"http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={api_key}&units={units_metric}").read())[2:-1])

weather_f = eval(str(urllib.request.urlopen(f"http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={api_key}&units={units_us}").read())[2:-1])

info_c = weather_c["weather"][0]["description"].capitalize()
info_f = weather_f["weather"][0]["description"].capitalize()
temp_c = int(float(weather_c["main"]["temp"]))
temp_f = int(float(weather_f["main"]["temp"]))
print("%s, %i °%s  /  %i °%s" % (info_c, temp_c, unit_key_c, temp_f, unit_key_f))
